name: smart_camera
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - pillow
      - fastapi[standard]
      - python-multipart
      - aiohttp[speedups]
      - uvicorn[standard]